sysdep.c: don't include <linux/if_tun.h> on Linux
Including <linux/if_tun.h> in sysdep.c is not necessary since sysdep.h
already includes <netinet/if_ether.h>. And this is actually
potentially harmful since both files redefine the same 'struct
ethhdr', causing the following build failure with the musl C library:

In file included from sysdep.h:28:0,
                 from sysdep.c:71:
.../buildroot/output/host/usr/arm-buildroot-linux-musleabihf/sysroot/usr/include/netinet/if_ether.h:96:8: error: redefinition of ‘struct ethhdr’
 struct ethhdr {
        ^
In file included from .../buildroot/output/host/usr/arm-buildroot-linux-musleabihf/sysroot/usr/include/linux/if_tun.h:20:0,
                 from sysdep.c:62:
.../buildroot/output/host/usr/arm-buildroot-linux-musleabihf/sysroot/usr/include/linux/if_ether.h:138:8: note: originally defined here
 struct ethhdr {
        ^

Original patch from:
http://git.alpinelinux.org/cgit/aports/tree/testing/vpnc/working.patch

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>