sysdep.h: don't assume <error.h> is available on all Linux platforms
The current logic in sysdep.h assumes that whenever you have __linux__
or __GLIBC__ defined, then <error.h> functionality is
available. However, the <error.h> functionality is a glibc-ism, not
available in more standard-conformant C libraries such as the musl C
library. With musl, __linux__ is defined (but of course not
__GLIBC__). With the current logic, sysdep.h assumes that <error.h> is
available, which isn't the case.

This patch therefore changes the logic to only use <error.h> when
__GLIBC__ is defined. It fixes the following build error:

In file included from tunip.c:87:0:
sysdep.h:41:19: fatal error: error.h: No such file or directory
 #include <error.h>

Original patch from
http://git.alpinelinux.org/cgit/aports/tree/testing/vpnc/working.patch.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>