config.c: add missing <sys/ttydefaults.h> include
This include is needed to get the definition of CEOT, otherwise the
build fails with:

config.c: In function ‘vpnc_getline’:
config.c:145:25: error: ‘CEOT’ undeclared (first use in this function)
   if (llen == 0 && c == CEOT)
                         ^

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>